import type { DatabaseShape } from './liensina.types'

export const databaseCollections: Array<keyof DatabaseShape> = [
  'users',
  'refreshSessions',
  'idempotencyRecords',
  'notifications',
  'roles',
  'schools',
  'teachers',
  'guardians',
  'students',
  'classes',
  'evaluations',
  'answerCards',
  'evaluationCorrections',
  'curriculumBases',
  'curriculumSkills',
  'assessmentPrograms',
  'assessmentMatrices',
  'assessmentDescriptors',
  'questions',
  'questionImportPlans',
  'lessonRecords',
  'roomReservations',
  'calendarEvents',
  'mealFoods',
  'mealManagements',
  'mealFoodRequests',
  'mealRequestHistory',
  'auditEvents',
]

export function createEmptyDatabase(): DatabaseShape {
  return {
    users: [],
    refreshSessions: [],
    idempotencyRecords: [],
    notifications: [],
    roles: [],
    schools: [],
    teachers: [],
    guardians: [],
    students: [],
    classes: [],
    evaluations: [],
    answerCards: [],
    evaluationCorrections: [],
    curriculumBases: [],
    curriculumSkills: [],
    assessmentPrograms: [],
    assessmentMatrices: [],
    assessmentDescriptors: [],
    questions: [],
    questionImportPlans: [],
    lessonRecords: [],
    roomReservations: [],
    calendarEvents: [],
    mealFoods: [],
    mealManagements: [],
    mealFoodRequests: [],
    mealRequestHistory: [],
    auditEvents: [],
  }
}
