import type { SeedQuestionInput } from './question-bank.seed'

export const additionalSeedQuestions: SeedQuestionInput[] = [
  {
    title: 'Localizacao de informacao em aviso escolar',
    context: 'AVISO: A reuniao de pais acontecera na sexta-feira, as 15h, na sala de leitura da escola.',
    statement: 'Onde acontecera a reuniao de pais?',
    explanation: 'O aviso informa que a reuniao ocorrera na sala de leitura da escola.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Na quadra da escola.', order: 1, isCorrect: false },
      { label: 'B', text: 'Na sala de leitura.', order: 2, isCorrect: true },
      { label: 'C', text: 'Na secretaria.', order: 3, isCorrect: false },
      { label: 'D', text: 'No patio.', order: 4, isCorrect: false },
      { label: 'E', text: 'Na biblioteca municipal.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF15LP03', description: 'Localizar informacoes explicitas em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D01', description: 'Localizar informacoes explicitas em um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 45, hasImage: false, hasTable: false, hasFormula: false, keywords: ['aviso', 'informacao explicita'] },
  },
  {
    title: 'Subtracao em situacao de compra',
    context: 'Lucas tinha R$ 50,00. Ele comprou um livro por R$ 32,00.',
    statement: 'Com quanto Lucas ficou apos a compra?',
    explanation: '50 - 32 = 18.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'R$ 12,00', order: 1, isCorrect: false },
      { label: 'B', text: 'R$ 16,00', order: 2, isCorrect: false },
      { label: 'C', text: 'R$ 18,00', order: 3, isCorrect: true },
      { label: 'D', text: 'R$ 20,00', order: 4, isCorrect: false },
      { label: 'E', text: 'R$ 22,00', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF05MA07', description: 'Resolver problemas de adicao e subtracao com numeros naturais e racionais.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D19', description: 'Resolver problema com numeros naturais envolvendo operacoes.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['subtracao', 'dinheiro'] },
  },
  {
    title: 'Inferencia em texto curto',
    context: 'Marina abriu a janela e viu o ceu escuro. Pegou rapidamente seu guarda-chuva antes de sair.',
    statement: 'Por que Marina pegou o guarda-chuva?',
    explanation: 'O ceu escuro indica possibilidade de chuva.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Porque estava fazendo sol.', order: 1, isCorrect: false },
      { label: 'B', text: 'Porque poderia chover.', order: 2, isCorrect: true },
      { label: 'C', text: 'Porque iria a praia.', order: 3, isCorrect: false },
      { label: 'D', text: 'Porque queria brincar.', order: 4, isCorrect: false },
      { label: 'E', text: 'Porque estava ventando dentro de casa.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF35LP04', description: 'Inferir informacoes implicitas em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D04', description: 'Inferir uma informacao implicita em um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['inferencia', 'chuva'] },
  },
  {
    title: 'Multiplicacao em organizacao de cadeiras',
    context: 'Em uma sala, foram organizadas 8 fileiras com 6 cadeiras em cada fileira.',
    statement: 'Quantas cadeiras ha ao todo?',
    explanation: '8 x 6 = 48.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '36', order: 1, isCorrect: false },
      { label: 'B', text: '42', order: 2, isCorrect: false },
      { label: 'C', text: '48', order: 3, isCorrect: true },
      { label: 'D', text: '54', order: 4, isCorrect: false },
      { label: 'E', text: '64', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF05MA08', description: 'Resolver problemas de multiplicacao e divisao com numeros naturais.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D19', description: 'Resolver problema com numeros naturais envolvendo operacoes.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['multiplicacao', 'organizacao retangular'] },
  },
  {
    title: 'Finalidade de cartaz',
    context: 'CARTAZ: Economize agua! Feche a torneira enquanto escova os dentes.',
    statement: 'Qual e a finalidade principal do cartaz?',
    explanation: 'O cartaz busca orientar e conscientizar sobre economia de agua.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Contar uma historia.', order: 1, isCorrect: false },
      { label: 'B', text: 'Ensinar uma receita.', order: 2, isCorrect: false },
      { label: 'C', text: 'Divulgar uma promocao.', order: 3, isCorrect: false },
      { label: 'D', text: 'Conscientizar sobre economia de agua.', order: 4, isCorrect: true },
      { label: 'E', text: 'Apresentar uma noticia esportiva.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF15LP01', description: 'Identificar a funcao social de textos que circulam em campos da vida social.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D09', description: 'Identificar a finalidade de textos de diferentes generos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 45, hasImage: false, hasTable: false, hasFormula: false, keywords: ['cartaz', 'finalidade', 'agua'] },
  },
  {
    title: 'Perimetro de retangulo',
    context: 'Um terreno retangular mede 12 metros de comprimento e 8 metros de largura.',
    statement: 'Qual e o perimetro desse terreno?',
    explanation: 'Perimetro = 12 + 8 + 12 + 8 = 40 metros.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '20 m', order: 1, isCorrect: false },
      { label: 'B', text: '32 m', order: 2, isCorrect: false },
      { label: 'C', text: '36 m', order: 3, isCorrect: false },
      { label: 'D', text: '40 m', order: 4, isCorrect: true },
      { label: 'E', text: '96 m', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF05MA20', description: 'Concluir, por meio de investigacoes, relacoes entre perimetro e area de figuras.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D11', description: 'Resolver problema envolvendo o calculo de perimetro de figuras planas.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['perimetro', 'retangulo'] },
  },
  {
    title: 'Comparacao de numeros decimais',
    context: 'Quatro alunos correram uma prova. Seus tempos foram: Ana 12,8 s; Bruno 13,1 s; Carla 12,5 s; Diego 13,0 s.',
    statement: 'Quem fez o menor tempo?',
    explanation: 'O menor numero decimal e 12,5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Ana', order: 1, isCorrect: false },
      { label: 'B', text: 'Bruno', order: 2, isCorrect: false },
      { label: 'C', text: 'Carla', order: 3, isCorrect: true },
      { label: 'D', text: 'Diego', order: 4, isCorrect: false },
      { label: 'E', text: 'Todos empataram.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF06MA01', description: 'Comparar, ordenar, ler e escrever numeros naturais e numeros racionais positivos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D21', description: 'Identificar diferentes representacoes e comparar numeros racionais.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['numeros decimais', 'comparacao'] },
  },
  {
    title: 'Tema de texto sobre alimentacao',
    context: 'Uma alimentacao equilibrada deve incluir frutas, verduras, cereais e proteinas. Esses alimentos ajudam o corpo a ter energia e a manter a saude.',
    statement: 'O tema principal do texto e',
    explanation: 'O texto fala sobre alimentacao equilibrada e saude.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'A pratica de esportes.', order: 1, isCorrect: false },
      { label: 'B', text: 'O uso de tecnologia.', order: 2, isCorrect: false },
      { label: 'C', text: 'A alimentacao equilibrada.', order: 3, isCorrect: true },
      { label: 'D', text: 'A economia de agua.', order: 4, isCorrect: false },
      { label: 'E', text: 'A leitura de livros.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP03', description: 'Identificar tema e informacoes relevantes em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D06', description: 'Identificar o tema de um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['tema', 'alimentacao'] },
  },
  {
    title: 'Divisao com resto',
    context: 'Uma professora precisa distribuir 58 lapis igualmente entre 6 grupos.',
    statement: 'Quantos lapis cada grupo recebera, se a distribuicao for feita igualmente, e quantos sobrarao?',
    explanation: '58 / 6 = 9, com resto 4.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '8 lapis e sobram 10.', order: 1, isCorrect: false },
      { label: 'B', text: '9 lapis e sobram 4.', order: 2, isCorrect: true },
      { label: 'C', text: '9 lapis e sobram 6.', order: 3, isCorrect: false },
      { label: 'D', text: '10 lapis e nao sobra nenhum.', order: 4, isCorrect: false },
      { label: 'E', text: '11 lapis e sobram 2.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF06MA03', description: 'Resolver problemas que envolvam calculos com numeros naturais.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D19', description: 'Resolver problema com numeros naturais envolvendo operacoes.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['divisao', 'resto'] },
  },
  {
    title: 'Sentido de expressao em contexto',
    context: 'Ao receber a noticia da vitoria, Joao ficou com um sorriso de orelha a orelha.',
    statement: "A expressao 'sorriso de orelha a orelha' indica que Joao estava",
    explanation: 'A expressao indica grande alegria.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'muito cansado.', order: 1, isCorrect: false },
      { label: 'B', text: 'muito alegre.', order: 2, isCorrect: true },
      { label: 'C', text: 'muito preocupado.', order: 3, isCorrect: false },
      { label: 'D', text: 'muito confuso.', order: 4, isCorrect: false },
      { label: 'E', text: 'muito atrasado.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF67LP06', description: 'Inferir o sentido de palavras ou expressoes em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D03', description: 'Inferir o sentido de uma palavra ou expressao.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['expressao', 'sentido figurado'] },
  },
  {
    title: 'Area de retangulo',
    context: 'Uma quadra retangular mede 20 metros de comprimento e 10 metros de largura.',
    statement: 'Qual e a area da quadra?',
    explanation: 'Area do retangulo = 20 x 10 = 200 m2.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '30 m2', order: 1, isCorrect: false },
      { label: 'B', text: '100 m2', order: 2, isCorrect: false },
      { label: 'C', text: '200 m2', order: 3, isCorrect: true },
      { label: 'D', text: '300 m2', order: 4, isCorrect: false },
      { label: 'E', text: '400 m2', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF06MA24', description: 'Resolver problemas que envolvam grandezas como comprimento, massa, tempo, temperatura, area e volume.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D12', description: 'Resolver problema envolvendo o calculo de area de figuras planas.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: true, keywords: ['area', 'retangulo'] },
  },
  {
    title: 'Porcentagem simples',
    context: 'Em uma turma com 40 alunos, 25% usam transporte escolar.',
    statement: 'Quantos alunos usam transporte escolar?',
    explanation: '25% de 40 e 10.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '5', order: 1, isCorrect: false },
      { label: 'B', text: '8', order: 2, isCorrect: false },
      { label: 'C', text: '10', order: 3, isCorrect: true },
      { label: 'D', text: '15', order: 4, isCorrect: false },
      { label: 'E', text: '20', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA02', description: 'Resolver problemas envolvendo porcentagens.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D16', description: 'Resolver problema envolvendo porcentagem.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: true, keywords: ['porcentagem'] },
  },
  {
    title: 'Fato e opiniao em texto informativo',
    context: 'A praca central foi reformada em 2024. Ela recebeu novos bancos, iluminacao e jardim. Para os moradores, ficou mais bonita.',
    statement: 'Qual trecho apresenta uma opiniao?',
    explanation: 'Dizer que a praca ficou mais bonita expressa opiniao.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'A praca central foi reformada em 2024.', order: 1, isCorrect: false },
      { label: 'B', text: 'Ela recebeu novos bancos.', order: 2, isCorrect: false },
      { label: 'C', text: 'Ela recebeu iluminacao.', order: 3, isCorrect: false },
      { label: 'D', text: 'Ela recebeu jardim.', order: 4, isCorrect: false },
      { label: 'E', text: 'Ficou mais bonita.', order: 5, isCorrect: true },
    ],
    skills: [{ code: 'EF69LP03', description: 'Identificar opinioes e posicionamentos em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D14', description: 'Distinguir fato de opiniao.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: false, keywords: ['fato', 'opiniao'] },
  },
  {
    title: 'Razao entre grandezas',
    context: 'Uma receita usa 2 copos de suco concentrado para 6 copos de agua.',
    statement: 'Qual e a razao entre suco concentrado e agua?',
    explanation: 'A razao e 2 para 6, que pode ser simplificada para 1 para 3.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '1 para 2', order: 1, isCorrect: false },
      { label: 'B', text: '1 para 3', order: 2, isCorrect: true },
      { label: 'C', text: '2 para 3', order: 3, isCorrect: false },
      { label: 'D', text: '3 para 1', order: 4, isCorrect: false },
      { label: 'E', text: '6 para 2', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA09', description: 'Resolver problemas que envolvam razao entre duas grandezas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D18', description: 'Resolver problema envolvendo razao e proporcao.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['razao', 'proporcao'] },
  },
  {
    title: 'Finalidade de noticia',
    context: 'A prefeitura iniciou nesta semana a campanha de vacinacao contra a gripe nas unidades de saude do municipio.',
    statement: 'A finalidade principal desse texto e',
    explanation: 'O texto informa um acontecimento de interesse publico.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'narrar uma aventura.', order: 1, isCorrect: false },
      { label: 'B', text: 'informar um fato.', order: 2, isCorrect: true },
      { label: 'C', text: 'ensinar uma brincadeira.', order: 3, isCorrect: false },
      { label: 'D', text: 'vender um produto.', order: 4, isCorrect: false },
      { label: 'E', text: 'descrever uma personagem.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF67LP10', description: 'Produzir e compreender noticias e textos jornalisticos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D09', description: 'Identificar a finalidade de textos de diferentes generos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 45, hasImage: false, hasTable: false, hasFormula: false, keywords: ['noticia', 'finalidade'] },
  },
  {
    title: 'Expressao algebrica',
    context: 'Um estacionamento cobra R$ 4,00 de entrada e R$ 3,00 por hora de permanencia.',
    statement: 'Qual expressao representa o valor V pago por h horas?',
    explanation: 'A taxa fixa e 4 e o valor por hora e 3h, entao V = 3h + 4.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'V = 4h + 3', order: 1, isCorrect: false },
      { label: 'B', text: 'V = 3h + 4', order: 2, isCorrect: true },
      { label: 'C', text: 'V = 7h', order: 3, isCorrect: false },
      { label: 'D', text: 'V = h + 7', order: 4, isCorrect: false },
      { label: 'E', text: 'V = 4 - 3h', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA13', description: 'Compreender a ideia de variavel e representar relacoes por expressoes algebricas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D30', description: 'Identificar expressao algebrica que representa uma situacao.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['algebra', 'expressao'] },
  },
  {
    title: 'Equacao do primeiro grau',
    context: 'Considere a equacao 2x + 7 = 19.',
    statement: 'Qual e o valor de x?',
    explanation: '2x + 7 = 19; 2x = 12; x = 6.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '4', order: 1, isCorrect: false },
      { label: 'B', text: '5', order: 2, isCorrect: false },
      { label: 'C', text: '6', order: 3, isCorrect: true },
      { label: 'D', text: '7', order: 4, isCorrect: false },
      { label: 'E', text: '8', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF08MA08', description: 'Resolver problemas representados por equacoes polinomiais de 1o grau.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D30', description: 'Resolver equacao simples do primeiro grau.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['equacao', 'primeiro grau'] },
  },
  {
    title: 'Relacao logico-discursiva',
    context: 'O aluno estudou bastante, portanto conseguiu melhorar sua nota.',
    statement: "A palavra 'portanto' estabelece uma relacao de",
    explanation: "'Portanto' indica conclusao.",
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'causa.', order: 1, isCorrect: false },
      { label: 'B', text: 'oposicao.', order: 2, isCorrect: false },
      { label: 'C', text: 'conclusao.', order: 3, isCorrect: true },
      { label: 'D', text: 'comparacao.', order: 4, isCorrect: false },
      { label: 'E', text: 'alternancia.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP56', description: 'Analisar mecanismos de coesao e relacoes logico-discursivas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D15', description: 'Estabelecer relacoes logico-discursivas presentes no texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['conectivo', 'conclusao'] },
  },
  {
    title: 'Porcentagem com aumento',
    context: 'Um produto custava R$ 200,00 e teve aumento de 10%.',
    statement: 'Qual passou a ser o preco do produto?',
    explanation: '10% de 200 e 20. Logo, 200 + 20 = 220.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'R$ 210,00', order: 1, isCorrect: false },
      { label: 'B', text: 'R$ 220,00', order: 2, isCorrect: true },
      { label: 'C', text: 'R$ 230,00', order: 3, isCorrect: false },
      { label: 'D', text: 'R$ 240,00', order: 4, isCorrect: false },
      { label: 'E', text: 'R$ 250,00', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF08MA04', description: 'Resolver problemas envolvendo porcentagens.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D16', description: 'Resolver problema envolvendo porcentagem.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['porcentagem', 'aumento'] },
  },
  {
    title: 'Efeito de sentido da pontuacao',
    context: "Leia a frase: 'Voce realmente fez isso?!'",
    statement: "O uso de '?!' sugere",
    explanation: 'A combinacao indica surpresa, espanto ou indignacao.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'surpresa ou espanto.', order: 1, isCorrect: true },
      { label: 'B', text: 'certeza absoluta.', order: 2, isCorrect: false },
      { label: 'C', text: 'calma e tranquilidade.', order: 3, isCorrect: false },
      { label: 'D', text: 'silencio prolongado.', order: 4, isCorrect: false },
      { label: 'E', text: 'negacao de uma ideia.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP47', description: 'Analisar efeitos de sentido decorrentes de recursos linguisticos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D17', description: 'Reconhecer efeito de sentido decorrente do uso da pontuacao.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['pontuacao', 'efeito de sentido'] },
  },
  {
    title: 'Sistema de equacoes simples',
    context: 'A soma de dois numeros e 20. Um deles e 6.',
    statement: 'Qual e o outro numero?',
    explanation: '20 - 6 = 14.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '10', order: 1, isCorrect: false },
      { label: 'B', text: '12', order: 2, isCorrect: false },
      { label: 'C', text: '14', order: 3, isCorrect: true },
      { label: 'D', text: '16', order: 4, isCorrect: false },
      { label: 'E', text: '18', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF08MA08', description: 'Resolver problemas representados por equacoes de 1o grau.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D30', description: 'Resolver situacao-problema envolvendo linguagem algebrica.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['algebra', 'soma'] },
  },
  {
    title: 'Teorema de Pitagoras',
    context: 'Um triangulo retangulo possui catetos medindo 9 cm e 12 cm.',
    statement: 'Qual e a medida da hipotenusa?',
    explanation: 'c2 = 9^2 + 12^2 = 81 + 144 = 225; c = 15.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '13 cm', order: 1, isCorrect: false },
      { label: 'B', text: '14 cm', order: 2, isCorrect: false },
      { label: 'C', text: '15 cm', order: 3, isCorrect: true },
      { label: 'D', text: '18 cm', order: 4, isCorrect: false },
      { label: 'E', text: '21 cm', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA13', description: 'Aplicar o Teorema de Pitagoras na resolucao de problemas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D10', description: 'Utilizar relacoes metricas no triangulo retangulo.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 120, hasImage: false, hasTable: false, hasFormula: true, keywords: ['Pitagoras', 'geometria'] },
  },
  {
    title: 'Tese de texto argumentativo',
    context: 'A leitura diaria deve ser incentivada nas escolas, pois amplia o vocabulario dos estudantes e melhora a compreensao de diferentes textos.',
    statement: 'Qual e a tese defendida no texto?',
    explanation: 'A ideia defendida e que a leitura diaria deve ser incentivada nas escolas.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'A leitura diaria deve ser incentivada nas escolas.', order: 1, isCorrect: true },
      { label: 'B', text: 'A leitura prejudica o vocabulario.', order: 2, isCorrect: false },
      { label: 'C', text: 'Os estudantes nao precisam ler textos diferentes.', order: 3, isCorrect: false },
      { label: 'D', text: 'A escola deve abandonar a leitura.', order: 4, isCorrect: false },
      { label: 'E', text: 'O vocabulario nao se relaciona a leitura.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF89LP04', description: 'Identificar tese e argumentos em textos argumentativos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D07', description: 'Identificar a tese de um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['tese', 'argumentacao'] },
  },
  {
    title: 'Funcao afim',
    context: 'Uma grafica cobra R$ 10,00 de taxa fixa mais R$ 0,50 por pagina impressa.',
    statement: 'Qual expressao representa o custo C para imprimir p paginas?',
    explanation: 'O custo e a taxa fixa somada ao valor por pagina: C = 0,50p + 10.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'C = 10p + 0,50', order: 1, isCorrect: false },
      { label: 'B', text: 'C = 0,50p + 10', order: 2, isCorrect: true },
      { label: 'C', text: 'C = 10p', order: 3, isCorrect: false },
      { label: 'D', text: 'C = p + 0,50', order: 4, isCorrect: false },
      { label: 'E', text: 'C = 10 - 0,50p', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA06', description: 'Compreender funcoes como relacoes de dependencia entre duas variaveis.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D33', description: 'Identificar expressao algebrica que representa uma funcao.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['funcao afim', 'modelagem'] },
  },
  {
    title: 'Relacao entre tese e argumento',
    context: 'O uso de bicicletas deve ser incentivado nas cidades, porque reduz a emissao de poluentes e contribui para a saude da populacao.',
    statement: "O trecho 'porque reduz a emissao de poluentes e contribui para a saude da populacao' apresenta",
    explanation: 'Esse trecho justifica a tese defendida.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'uma conclusao sem relacao com o texto.', order: 1, isCorrect: false },
      { label: 'B', text: 'um argumento que sustenta a tese.', order: 2, isCorrect: true },
      { label: 'C', text: 'uma opiniao contraria a tese.', order: 3, isCorrect: false },
      { label: 'D', text: 'uma descricao de personagem.', order: 4, isCorrect: false },
      { label: 'E', text: 'uma pergunta indireta.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF89LP04', description: 'Identificar argumentos e relacoes entre tese e argumentos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D08', description: 'Estabelecer relacao entre tese e argumentos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['argumento', 'tese'] },
  },
  {
    title: 'Probabilidade simples',
    context: 'Em uma caixa ha 4 bolas amarelas, 3 bolas azuis e 3 bolas vermelhas.',
    statement: 'Qual e a probabilidade de retirar uma bola azul?',
    explanation: 'Sao 3 bolas azuis em um total de 10 bolas. Probabilidade = 3/10.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '1/10', order: 1, isCorrect: false },
      { label: 'B', text: '2/10', order: 2, isCorrect: false },
      { label: 'C', text: '3/10', order: 3, isCorrect: true },
      { label: 'D', text: '4/10', order: 4, isCorrect: false },
      { label: 'E', text: '7/10', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA20', description: 'Reconhecer e calcular probabilidade de eventos aleatorios.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D42', description: 'Resolver problema envolvendo probabilidade simples.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['probabilidade'] },
  },
  {
    title: 'Tabela de frequencia',
    context: 'Em uma pesquisa, 12 alunos preferem futebol, 8 preferem volei, 5 preferem basquete e 5 preferem handebol.',
    statement: 'Qual esporte foi escolhido pela maior quantidade de alunos?',
    explanation: 'Futebol teve 12 escolhas, a maior frequencia.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Futebol', order: 1, isCorrect: true },
      { label: 'B', text: 'Volei', order: 2, isCorrect: false },
      { label: 'C', text: 'Basquete', order: 3, isCorrect: false },
      { label: 'D', text: 'Handebol', order: 4, isCorrect: false },
      { label: 'E', text: 'Todos tiveram a mesma quantidade.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF05MA24', description: 'Interpretar dados estatisticos apresentados em textos, tabelas e graficos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D27', description: 'Ler informacoes apresentadas em tabelas ou graficos.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: true, hasFormula: false, keywords: ['tabela', 'frequencia'] },
  },
  {
    title: 'Uso de pronome',
    context: 'Carla comprou um caderno novo. Ela usara o material nas aulas de Ciencias.',
    statement: "No texto, a palavra 'Ela' se refere a",
    explanation: "O pronome 'Ela' retoma Carla.",
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Carla.', order: 1, isCorrect: true },
      { label: 'B', text: 'caderno.', order: 2, isCorrect: false },
      { label: 'C', text: 'material.', order: 3, isCorrect: false },
      { label: 'D', text: 'aulas.', order: 4, isCorrect: false },
      { label: 'E', text: 'Ciencias.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF67LP25', description: 'Reconhecer mecanismos de coesao referencial em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D02', description: 'Estabelecer relacoes entre partes de um texto por mecanismos de coesao.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 45, hasImage: false, hasTable: false, hasFormula: false, keywords: ['pronome', 'coesao'] },
  },
  {
    title: 'Numeros inteiros em temperatura',
    context: 'Em uma cidade, a temperatura pela manha era de -2 C. A tarde, subiu 7 C.',
    statement: 'Qual foi a temperatura a tarde?',
    explanation: '-2 + 7 = 5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '-9 C', order: 1, isCorrect: false },
      { label: 'B', text: '-5 C', order: 2, isCorrect: false },
      { label: 'C', text: '0 C', order: 3, isCorrect: false },
      { label: 'D', text: '5 C', order: 4, isCorrect: true },
      { label: 'E', text: '9 C', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA03', description: 'Comparar e ordenar numeros inteiros e resolver problemas com inteiros.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D20', description: 'Resolver problema envolvendo numeros inteiros.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: true, keywords: ['inteiros', 'temperatura'] },
  },
  {
    title: 'Comparacao entre textos',
    context: 'Texto 1: A caminhada diaria ajuda a melhorar a saude.\nTexto 2: Praticar exercicios regularmente contribui para o bem-estar fisico e mental.',
    statement: 'Os dois textos tem em comum a ideia de que',
    explanation: 'Ambos defendem beneficios da atividade fisica.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'a atividade fisica traz beneficios.', order: 1, isCorrect: true },
      { label: 'B', text: 'a caminhada deve ser evitada.', order: 2, isCorrect: false },
      { label: 'C', text: 'o exercicio prejudica a saude.', order: 3, isCorrect: false },
      { label: 'D', text: 'o bem-estar depende apenas da alimentacao.', order: 4, isCorrect: false },
      { label: 'E', text: 'a saude nao se relaciona ao movimento.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP30', description: 'Comparar textos que tratam do mesmo tema.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D20', description: 'Reconhecer diferentes formas de tratar uma informacao na comparacao de textos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['comparacao de textos'] },
  },
  {
    title: 'Notacao cientifica simples',
    context: 'A distancia aproximada entre duas cidades e 300.000 metros.',
    statement: 'Como esse numero pode ser escrito em notacao cientifica?',
    explanation: '300.000 = 3 x 10^5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '3 x 10^2', order: 1, isCorrect: false },
      { label: 'B', text: '3 x 10^3', order: 2, isCorrect: false },
      { label: 'C', text: '3 x 10^4', order: 3, isCorrect: false },
      { label: 'D', text: '3 x 10^5', order: 4, isCorrect: true },
      { label: 'E', text: '3 x 10^6', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF08MA01', description: 'Efetuar calculos com potencias de expoentes inteiros e aplicar notacao cientifica.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D26', description: 'Resolver problema envolvendo potencias e notacao cientifica.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['notacao cientifica', 'potencia'] },
  },
  {
    title: 'Volume de bloco retangular',
    context: 'Uma caixa tem 5 cm de comprimento, 4 cm de largura e 3 cm de altura.',
    statement: 'Qual e o volume da caixa?',
    explanation: 'Volume = 5 x 4 x 3 = 60 cm3.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '12 cm3', order: 1, isCorrect: false },
      { label: 'B', text: '20 cm3', order: 2, isCorrect: false },
      { label: 'C', text: '35 cm3', order: 3, isCorrect: false },
      { label: 'D', text: '60 cm3', order: 4, isCorrect: true },
      { label: 'E', text: '80 cm3', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA19', description: 'Resolver problemas envolvendo medidas de volume.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D13', description: 'Resolver problema envolvendo volume de solidos geometricos.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['volume', 'bloco retangular'] },
  },
  {
    title: 'Efeito de ironia',
    context: "Depois de esperar duas horas pelo onibus, Marcos disse: 'Que transporte rapido!'",
    statement: 'A fala de Marcos apresenta efeito de',
    explanation: 'Ele diz o contrario do que realmente quer expressar, caracterizando ironia.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'ironia.', order: 1, isCorrect: true },
      { label: 'B', text: 'explicacao cientifica.', order: 2, isCorrect: false },
      { label: 'C', text: 'ordem direta.', order: 3, isCorrect: false },
      { label: 'D', text: 'descricao neutra.', order: 4, isCorrect: false },
      { label: 'E', text: 'enumeracao.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF89LP37', description: 'Analisar efeitos de sentido em textos multissemioticos e verbais.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D18', description: 'Reconhecer efeito de sentido decorrente de ironia ou humor.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['ironia', 'efeito de sentido'] },
  },
  {
    title: 'Media aritmetica',
    context: 'As notas de Clara foram 6, 7, 8 e 9.',
    statement: 'Qual foi a media aritmetica das notas?',
    explanation: '(6 + 7 + 8 + 9) / 4 = 30 / 4 = 7,5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '7,0', order: 1, isCorrect: false },
      { label: 'B', text: '7,5', order: 2, isCorrect: true },
      { label: 'C', text: '8,0', order: 3, isCorrect: false },
      { label: 'D', text: '8,5', order: 4, isCorrect: false },
      { label: 'E', text: '9,0', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA22', description: 'Escolher e construir graficos e calcular medidas de tendencia central.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D40', description: 'Resolver problema envolvendo media aritmetica.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: true, keywords: ['media', 'estatistica'] },
  },
  {
    title: 'Identificacao de genero textual',
    context: 'Ingredientes: 2 ovos, 1 xicara de leite, 2 xicaras de farinha. Modo de preparo: misture tudo e leve ao forno por 30 minutos.',
    statement: 'Esse texto pertence ao genero',
    explanation: 'O texto apresenta ingredientes e modo de preparo, caracteristicas de receita.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'noticia.', order: 1, isCorrect: false },
      { label: 'B', text: 'receita.', order: 2, isCorrect: true },
      { label: 'C', text: 'poema.', order: 3, isCorrect: false },
      { label: 'D', text: 'bilhete.', order: 4, isCorrect: false },
      { label: 'E', text: 'fabula.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF15LP01', description: 'Identificar generos textuais e suas funcoes sociais.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D09', description: 'Identificar a finalidade de textos de diferentes generos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 45, hasImage: false, hasTable: false, hasFormula: false, keywords: ['receita', 'genero textual'] },
  },
  {
    title: 'Escala simples',
    context: 'Em um mapa, 1 cm representa 5 km. A distancia entre duas cidades no mapa e de 4 cm.',
    statement: 'Qual e a distancia real entre as cidades?',
    explanation: '4 x 5 = 20 km.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '9 km', order: 1, isCorrect: false },
      { label: 'B', text: '15 km', order: 2, isCorrect: false },
      { label: 'C', text: '20 km', order: 3, isCorrect: true },
      { label: 'D', text: '25 km', order: 4, isCorrect: false },
      { label: 'E', text: '40 km', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA17', description: 'Resolver problemas envolvendo grandezas proporcionais e escala.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D18', description: 'Resolver problema envolvendo proporcionalidade.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['escala', 'proporcionalidade'] },
  },
]
