import type {
  AssessmentDescriptor,
  AssessmentMatrix,
  AssessmentProgram,
  CurriculumBase,
  CurriculumSkill,
  DatabaseShape,
  DescriptorRelevance,
  Difficulty,
  EducationStage,
  Question,
  QuestionImportPlan,
  QuestionMetadata,
  QuestionOption,
  QuestionSourceType,
  QuestionStatus,
  QuestionType,
  QuestionVisibility,
  SkillRelevance,
} from './liensina.types'
import { additionalSeedQuestions } from './question-bank-extra.seed'

export type SeedQuestionInput = {
  title: string
  context: string
  statement: string
  explanation: string
  type: QuestionType
  stage: EducationStage
  gradeLevel: string
  area: string
  component: string
  subject: string
  difficulty: Difficulty
  sourceType: QuestionSourceType
  sourceName: string
  sourceYear: number
  visibility: QuestionVisibility
  status: QuestionStatus
  options: Array<Pick<QuestionOption, 'label' | 'text' | 'order' | 'isCorrect'>>
  skills: Array<{
    code: string
    description: string
    relevance: SkillRelevance
  }>
  descriptors: Array<{
    program: string
    code: string
    description: string
    subject: string
    relevance: DescriptorRelevance
  }>
  metadata: QuestionMetadata
}

export type QuestionBankSeed = Pick<
  DatabaseShape,
  'curriculumBases' |
  'curriculumSkills' |
  'assessmentPrograms' |
  'assessmentMatrices' |
  'assessmentDescriptors' |
  'questions' |
  'questionImportPlans'
>

const seedCreatedAt = '2026-05-06T00:00:00.000Z'
const curriculumBaseId = 'curriculum-base-bncc'
const systemUserId = 'system-liensina'
const globalSchoolId = 'global-school'
const globalNetworkId = 'global-network'

const seedQuestions: SeedQuestionInput[] = [
  {
    title: 'Leitura de informacao explicita em bilhete',
    context: 'Leia o bilhete:\n\nAna,\nNao esqueca de levar o livro de Ciencias amanha. A professora pediu que todos entreguem o resumo na primeira aula.\nBeijos,\nMamae.',
    statement: 'De acordo com o bilhete, o que Ana deve levar amanha?',
    explanation: "A informacao esta explicita no trecho: 'Nao esqueca de levar o livro de Ciencias amanha'.",
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'O caderno de Matematica.', order: 1, isCorrect: false },
      { label: 'B', text: 'O livro de Ciencias.', order: 2, isCorrect: true },
      { label: 'C', text: 'O resumo de Historia.', order: 3, isCorrect: false },
      { label: 'D', text: 'A agenda escolar.', order: 4, isCorrect: false },
      { label: 'E', text: 'O uniforme de Educacao Fisica.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF15LP03', description: 'Localizar informacoes explicitas em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D01', description: 'Localizar informacoes explicitas em um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['bilhete', 'informacao explicita', 'leitura'] },
  },
  {
    title: 'Adicao com numeros decimais',
    context: 'Em uma papelaria, Julia comprou um caderno por R$ 12,50 e uma caneta por R$ 3,75.',
    statement: 'Quanto Julia gastou ao todo?',
    explanation: 'Somando 12,50 + 3,75, obtemos 16,25.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'R$ 14,25', order: 1, isCorrect: false },
      { label: 'B', text: 'R$ 15,25', order: 2, isCorrect: false },
      { label: 'C', text: 'R$ 16,25', order: 3, isCorrect: true },
      { label: 'D', text: 'R$ 17,25', order: 4, isCorrect: false },
      { label: 'E', text: 'R$ 18,25', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF05MA07', description: 'Resolver e elaborar problemas de adicao e subtracao com numeros naturais e racionais na representacao decimal finita.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D23', description: 'Resolver problema com numeros racionais envolvendo as operacoes fundamentais.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['numeros decimais', 'adicao', 'situacao-problema'] },
  },
  {
    title: 'Inferencia em pequeno texto narrativo',
    context: "Pedro chegou a sala com o cabelo molhado, segurando o guarda-chuva fechado. Ao sentar, disse: 'Ainda bem que trouxe uma blusa extra'.",
    statement: 'O que provavelmente aconteceu com Pedro antes de chegar a sala?',
    explanation: 'Pelo cabelo molhado, guarda-chuva e fala sobre roupa extra, pode-se inferir que ele pegou chuva.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '5o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'Ele nadou antes da aula.', order: 1, isCorrect: false },
      { label: 'B', text: 'Ele pegou chuva no caminho.', order: 2, isCorrect: true },
      { label: 'C', text: 'Ele esqueceu o material em casa.', order: 3, isCorrect: false },
      { label: 'D', text: 'Ele chegou atrasado por causa do transito.', order: 4, isCorrect: false },
      { label: 'E', text: 'Ele lavou o cabelo na escola.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF35LP04', description: 'Inferir informacoes implicitas em textos lidos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D04', description: 'Inferir uma informacao implicita em um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: false, keywords: ['inferencia', 'texto narrativo', 'informacao implicita'] },
  },
  {
    title: 'Fracoes equivalentes',
    context: 'Observe as fracoes abaixo.',
    statement: 'Qual fracao e equivalente a 1/2?',
    explanation: 'A fracao 2/4 representa a mesma parte que 1/2, pois numerador e denominador foram multiplicados por 2.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '1/3', order: 1, isCorrect: false },
      { label: 'B', text: '2/4', order: 2, isCorrect: true },
      { label: 'C', text: '3/5', order: 3, isCorrect: false },
      { label: 'D', text: '4/6', order: 4, isCorrect: false },
      { label: 'E', text: '5/8', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF06MA07', description: 'Compreender, comparar e ordenar fracoes associadas as ideias de partes de inteiros e resultado de divisao.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D21', description: 'Identificar diferentes representacoes de um mesmo numero racional.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: true, keywords: ['fracoes', 'equivalencia', 'numeros racionais'] },
  },
  {
    title: 'Tema de texto informativo',
    context: 'A reciclagem ajuda a reduzir a quantidade de lixo enviado aos aterros. Alem disso, permite reaproveitar materiais como papel, vidro, plastico e metal, economizando recursos naturais.',
    statement: 'Qual e o tema principal do texto?',
    explanation: 'O texto trata principalmente da importancia e dos beneficios da reciclagem.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '6o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'A producao de vidro.', order: 1, isCorrect: false },
      { label: 'B', text: 'A importancia da reciclagem.', order: 2, isCorrect: true },
      { label: 'C', text: 'O aumento dos aterros.', order: 3, isCorrect: false },
      { label: 'D', text: 'O uso de metais na industria.', order: 4, isCorrect: false },
      { label: 'E', text: 'A venda de papel reciclado.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP03', description: 'Identificar, em textos, tema, tese e informacoes relevantes.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D06', description: 'Identificar o tema de um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['tema', 'texto informativo', 'reciclagem'] },
  },
  {
    title: 'Porcentagem em desconto',
    context: 'Uma mochila custa R$ 120,00. Em uma promocao, ela recebeu desconto de 25%.',
    statement: 'Qual foi o valor do desconto?',
    explanation: '25% de 120 corresponde a 1/4 de 120, ou seja, R$ 30,00.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'R$ 20,00', order: 1, isCorrect: false },
      { label: 'B', text: 'R$ 25,00', order: 2, isCorrect: false },
      { label: 'C', text: 'R$ 30,00', order: 3, isCorrect: true },
      { label: 'D', text: 'R$ 35,00', order: 4, isCorrect: false },
      { label: 'E', text: 'R$ 40,00', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF07MA02', description: 'Resolver e elaborar problemas que envolvam porcentagens, como acrescimos e decrescimos simples.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D16', description: 'Resolver problema envolvendo porcentagem.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['porcentagem', 'desconto', 'problema'] },
  },
  {
    title: 'Sentido de palavra pelo contexto',
    context: 'Depois de caminhar por horas, os viajantes encontraram uma fonte de agua cristalina e mataram a sede.',
    statement: "No texto, a palavra 'cristalina' indica que a agua era",
    explanation: "No contexto, 'cristalina' significa limpida, clara, transparente.",
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '7o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'escura.', order: 1, isCorrect: false },
      { label: 'B', text: 'gelada.', order: 2, isCorrect: false },
      { label: 'C', text: 'suja.', order: 3, isCorrect: false },
      { label: 'D', text: 'clara.', order: 4, isCorrect: true },
      { label: 'E', text: 'salgada.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF67LP06', description: 'Inferir o sentido de palavras ou expressoes em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D03', description: 'Inferir o sentido de uma palavra ou expressao.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['vocabulario', 'inferencia', 'sentido de palavra'] },
  },
  {
    title: 'Equacao do primeiro grau',
    context: 'Considere a equacao: 3x + 5 = 20.',
    statement: 'Qual e o valor de x?',
    explanation: '3x + 5 = 20; 3x = 15; x = 5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '3', order: 1, isCorrect: false },
      { label: 'B', text: '4', order: 2, isCorrect: false },
      { label: 'C', text: '5', order: 3, isCorrect: true },
      { label: 'D', text: '6', order: 4, isCorrect: false },
      { label: 'E', text: '7', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF08MA08', description: 'Resolver e elaborar problemas que possam ser representados por equacoes polinomiais de 1o grau.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D30', description: 'Calcular o valor numerico de uma expressao algebrica ou resolver equacao simples.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['equacao', 'algebra', 'primeiro grau'] },
  },
  {
    title: 'Fato e opiniao',
    context: 'O Parque Municipal foi inaugurado em 2015. Ele possui pista de caminhada, lago e area para piquenique. Para muitos moradores, e o lugar mais agradavel da cidade.',
    statement: 'Qual trecho apresenta uma opiniao?',
    explanation: "Dizer que e 'o lugar mais agradavel da cidade' expressa avaliacao subjetiva.",
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '8o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'O Parque Municipal foi inaugurado em 2015.', order: 1, isCorrect: false },
      { label: 'B', text: 'Ele possui pista de caminhada.', order: 2, isCorrect: false },
      { label: 'C', text: 'Ele possui lago.', order: 3, isCorrect: false },
      { label: 'D', text: 'Ele possui area para piquenique.', order: 4, isCorrect: false },
      { label: 'E', text: 'E o lugar mais agradavel da cidade.', order: 5, isCorrect: true },
    ],
    skills: [{ code: 'EF69LP03', description: 'Identificar informacoes, opinioes e posicionamentos em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D14', description: 'Distinguir fato de opiniao relativa a um fato.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: false, keywords: ['fato', 'opiniao', 'texto informativo'] },
  },
  {
    title: 'Teorema de Pitagoras em situacao-problema',
    context: 'Uma escada esta apoiada em uma parede. A base da escada esta a 6 metros da parede, e o topo alcanca 8 metros de altura.',
    statement: 'Qual e o comprimento da escada?',
    explanation: 'Pelo Teorema de Pitagoras: c2 = 62 + 82 = 36 + 64 = 100; c = 10.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Matematica',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '8 m', order: 1, isCorrect: false },
      { label: 'B', text: '9 m', order: 2, isCorrect: false },
      { label: 'C', text: '10 m', order: 3, isCorrect: true },
      { label: 'D', text: '12 m', order: 4, isCorrect: false },
      { label: 'E', text: '14 m', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF09MA13', description: 'Demonstrar relacoes metricas no triangulo retangulo, incluindo o Teorema de Pitagoras, e aplica-las na resolucao de problemas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D10', description: 'Utilizar relacoes metricas no triangulo retangulo para resolver problemas.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 120, hasImage: false, hasTable: false, hasFormula: true, keywords: ['Pitagoras', 'triangulo retangulo', 'geometria'] },
  },
  {
    title: 'Efeito de sentido da pontuacao',
    context: "Leia a frase:\n\n'Voce terminou o trabalho?!'",
    statement: 'O uso combinado de ponto de interrogacao e exclamacao indica',
    explanation: 'A combinacao ?! reforca surpresa, espanto ou indignacao diante da pergunta.',
    type: 'MULTIPLE_CHOICE',
    stage: 'FUNDAMENTAL',
    gradeLevel: '9o ano',
    area: 'Linguagens',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'ordem direta.', order: 1, isCorrect: false },
      { label: 'B', text: 'duvida sem emocao.', order: 2, isCorrect: false },
      { label: 'C', text: 'surpresa ou espanto.', order: 3, isCorrect: true },
      { label: 'D', text: 'negacao absoluta.', order: 4, isCorrect: false },
      { label: 'E', text: 'indicacao de silencio.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EF69LP47', description: 'Analisar efeitos de sentido decorrentes de recursos linguisticos e multissemioticos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D17', description: 'Reconhecer o efeito de sentido decorrente do uso da pontuacao e de outras notacoes.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['pontuacao', 'efeito de sentido', 'interrogacao', 'exclamacao'] },
  },
  {
    title: 'Funcao afim em corrida por aplicativo',
    context: 'Um aplicativo de transporte cobra R$ 5,00 de taxa fixa mais R$ 2,00 por quilometro rodado.',
    statement: 'Qual expressao representa o valor V, em reais, de uma corrida de x quilometros?',
    explanation: 'A taxa fixa e 5 e o valor variavel e 2 por quilometro, entao V = 2x + 5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '1a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'V = 5x + 2', order: 1, isCorrect: false },
      { label: 'B', text: 'V = 2x + 5', order: 2, isCorrect: true },
      { label: 'C', text: 'V = 7x', order: 3, isCorrect: false },
      { label: 'D', text: 'V = x + 7', order: 4, isCorrect: false },
      { label: 'E', text: 'V = 5x - 2', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT302', description: 'Construir modelos empregando funcoes polinomiais de 1o ou 2o graus para resolver problemas em contextos diversos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D33', description: 'Identificar a expressao algebrica que modela uma situacao-problema.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['funcao afim', 'modelagem', 'expressao algebrica'] },
  },
  {
    title: 'Interpretacao critica de grafico percentual',
    context: 'Uma pesquisa com 200 estudantes mostrou que 40% preferem estudar com videoaulas, 35% preferem livros e 25% preferem resumos.',
    statement: 'Quantos estudantes preferem estudar com videoaulas?',
    explanation: '40% de 200 e 80.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '1a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '60', order: 1, isCorrect: false },
      { label: 'B', text: '70', order: 2, isCorrect: false },
      { label: 'C', text: '80', order: 3, isCorrect: true },
      { label: 'D', text: '90', order: 4, isCorrect: false },
      { label: 'E', text: '100', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT101', description: 'Interpretar criticamente situacoes economicas, sociais e fatos relativos as Ciencias da Natureza que envolvam variacao de grandezas.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D16', description: 'Resolver problema envolvendo porcentagem.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 75, hasImage: false, hasTable: false, hasFormula: true, keywords: ['porcentagem', 'interpretacao de dados', 'pesquisa'] },
  },
  {
    title: 'Tese em texto argumentativo',
    context: 'O uso consciente da internet deve ser incentivado nas escolas, pois contribui para a pesquisa, a comunicacao e o desenvolvimento da autonomia dos estudantes. No entanto, e necessario orientar os alunos sobre seguranca digital e confiabilidade das informacoes.',
    statement: 'Qual e a tese defendida no texto?',
    explanation: 'A tese e a ideia central defendida: o uso consciente da internet deve ser incentivado nas escolas.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '1a serie',
    area: 'Linguagens e suas Tecnologias',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'A internet deve ser proibida nas escolas.', order: 1, isCorrect: false },
      { label: 'B', text: 'O uso consciente da internet deve ser incentivado nas escolas.', order: 2, isCorrect: true },
      { label: 'C', text: 'A comunicacao digital prejudica a autonomia dos estudantes.', order: 3, isCorrect: false },
      { label: 'D', text: 'Os alunos nao devem realizar pesquisas online.', order: 4, isCorrect: false },
      { label: 'E', text: 'A seguranca digital e irrelevante para a aprendizagem.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13LP02', description: 'Estabelecer relacoes entre as partes do texto, considerando a construcao composicional e os efeitos de sentido.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D07', description: 'Identificar a tese de um texto.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['tese', 'argumentacao', 'internet'] },
  },
  {
    title: 'Funcao quadratica e ponto maximo',
    context: 'A altura h, em metros, de uma bola apos t segundos e dada por h(t) = -t2 + 4t.',
    statement: 'Qual e a altura maxima atingida pela bola?',
    explanation: 'O vertice ocorre em t = -b/2a = -4/(2*-1) = 2. Entao h(2) = -4 + 8 = 4.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '2a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '2 m', order: 1, isCorrect: false },
      { label: 'B', text: '3 m', order: 2, isCorrect: false },
      { label: 'C', text: '4 m', order: 3, isCorrect: true },
      { label: 'D', text: '5 m', order: 4, isCorrect: false },
      { label: 'E', text: '8 m', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT302', description: 'Construir modelos empregando funcoes polinomiais de 1o ou 2o graus para resolver problemas em contextos diversos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D34', description: 'Resolver problema envolvendo funcao quadratica.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 150, hasImage: false, hasTable: false, hasFormula: true, keywords: ['funcao quadratica', 'vertice', 'altura maxima'] },
  },
  {
    title: 'Relacao entre textos',
    context: "Texto 1: 'O transporte coletivo reduz o numero de carros nas ruas e pode diminuir a emissao de poluentes.'\n\nTexto 2: 'Investir em onibus eletricos e uma alternativa para tornar o transporte urbano menos poluente.'",
    statement: 'Os dois textos apresentam em comum a ideia de que',
    explanation: 'Ambos tratam de transporte urbano e reducao de impactos ambientais.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '2a serie',
    area: 'Linguagens e suas Tecnologias',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'o transporte urbano pode contribuir para reduzir a poluicao.', order: 1, isCorrect: true },
      { label: 'B', text: 'os carros particulares sao mais economicos que os onibus.', order: 2, isCorrect: false },
      { label: 'C', text: 'os onibus eletricos aumentam a emissao de poluentes.', order: 3, isCorrect: false },
      { label: 'D', text: 'o transporte coletivo deve ser substituido por bicicletas.', order: 4, isCorrect: false },
      { label: 'E', text: 'as cidades nao devem investir em mobilidade.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13LP03', description: 'Analisar relacoes de intertextualidade e posicionamentos em textos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D20', description: 'Reconhecer diferentes formas de tratar uma informacao na comparacao de textos.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 120, hasImage: false, hasTable: false, hasFormula: false, keywords: ['relacao entre textos', 'intertextualidade', 'mobilidade urbana'] },
  },
  {
    title: 'Probabilidade simples',
    context: 'Em uma urna ha 3 bolas vermelhas, 2 azuis e 5 verdes, todas do mesmo tamanho.',
    statement: 'Qual e a probabilidade de retirar, ao acaso, uma bola azul?',
    explanation: 'Ha 2 bolas azuis em um total de 10 bolas. Logo, a probabilidade e 2/10 = 1/5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '2a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '1/10', order: 1, isCorrect: false },
      { label: 'B', text: '1/5', order: 2, isCorrect: true },
      { label: 'C', text: '1/2', order: 3, isCorrect: false },
      { label: 'D', text: '2/5', order: 4, isCorrect: false },
      { label: 'E', text: '3/10', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT311', description: 'Identificar e descrever o espaco amostral de eventos aleatorios, realizando contagem das possibilidades.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D42', description: 'Resolver problema envolvendo probabilidade simples.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['probabilidade', 'urna', 'fracao'] },
  },
  {
    title: 'Juros simples',
    context: 'Uma pessoa aplicou R$ 1.000,00 a juros simples de 2% ao mes durante 5 meses.',
    statement: 'Qual sera o valor dos juros ao final desse periodo?',
    explanation: 'J = C * i * t = 1000 * 0,02 * 5 = 100.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '3a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'R$ 50,00', order: 1, isCorrect: false },
      { label: 'B', text: 'R$ 80,00', order: 2, isCorrect: false },
      { label: 'C', text: 'R$ 100,00', order: 3, isCorrect: true },
      { label: 'D', text: 'R$ 120,00', order: 4, isCorrect: false },
      { label: 'E', text: 'R$ 200,00', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT303', description: 'Interpretar e comparar situacoes que envolvam juros simples e compostos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D16', description: 'Resolver problema envolvendo porcentagem em contexto financeiro.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 120, hasImage: false, hasTable: false, hasFormula: true, keywords: ['juros simples', 'porcentagem', 'educacao financeira'] },
  },
  {
    title: 'Coesao textual por conectivo',
    context: 'A escola ampliou a biblioteca, pois muitos estudantes precisavam de um espaco adequado para pesquisa.',
    statement: "No texto, a palavra 'pois' estabelece ideia de",
    explanation: "O conectivo 'pois' introduz uma justificativa ou causa.",
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '3a serie',
    area: 'Linguagens e suas Tecnologias',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'oposicao.', order: 1, isCorrect: false },
      { label: 'B', text: 'conclusao.', order: 2, isCorrect: false },
      { label: 'C', text: 'causa ou justificativa.', order: 3, isCorrect: true },
      { label: 'D', text: 'comparacao.', order: 4, isCorrect: false },
      { label: 'E', text: 'alternancia.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13LP08', description: 'Analisar elementos de coesao e coerencia na construcao textual.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D15', description: 'Estabelecer relacoes logico-discursivas presentes no texto, marcadas por conjuncoes, adverbios etc.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['coesao', 'conectivo', 'relacao logico-discursiva'] },
  },
  {
    title: 'Analise de media aritmetica',
    context: 'As notas de um estudante em quatro avaliacoes foram: 6,0; 7,5; 8,0; 8,5.',
    statement: 'Qual foi a media aritmetica dessas notas?',
    explanation: 'A media e (6 + 7,5 + 8 + 8,5) / 4 = 30 / 4 = 7,5.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '3a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '7,0', order: 1, isCorrect: false },
      { label: 'B', text: '7,25', order: 2, isCorrect: false },
      { label: 'C', text: '7,5', order: 3, isCorrect: true },
      { label: 'D', text: '8,0', order: 4, isCorrect: false },
      { label: 'E', text: '8,5', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT316', description: 'Resolver e elaborar problemas envolvendo medidas de tendencia central e dispersao.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D40', description: 'Resolver problema envolvendo media aritmetica.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: true, keywords: ['media aritmetica', 'estatistica', 'notas'] },
  },
  {
    title: 'Progressao aritmetica',
    context: 'A sequencia numerica 4, 7, 10, 13, ... segue um padrao.',
    statement: 'Qual e o proximo termo dessa sequencia?',
    explanation: 'A sequencia aumenta de 3 em 3. Depois de 13, vem 16.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '3a serie',
    area: 'Matematica e suas Tecnologias',
    component: 'Matematica',
    subject: 'Matematica',
    difficulty: 'EASY',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: '14', order: 1, isCorrect: false },
      { label: 'B', text: '15', order: 2, isCorrect: false },
      { label: 'C', text: '16', order: 3, isCorrect: true },
      { label: 'D', text: '17', order: 4, isCorrect: false },
      { label: 'E', text: '18', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13MAT507', description: 'Identificar e associar progressoes aritmeticas a funcoes afins de dominios discretos.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D32', description: 'Identificar regularidades em sequencias numericas.', subject: 'Matematica', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 60, hasImage: false, hasTable: false, hasFormula: false, keywords: ['sequencia', 'progressao aritmetica', 'regularidade'] },
  },
  {
    title: 'Relacao entre opiniao e argumento',
    context: 'A pratica de esportes deve ser incentivada entre os jovens, porque contribui para a saude fisica, melhora a convivencia em grupo e ajuda na disciplina.',
    statement: "No texto, o trecho 'porque contribui para a saude fisica, melhora a convivencia em grupo e ajuda na disciplina' funciona como",
    explanation: 'Esse trecho apresenta razoes que sustentam a opiniao defendida.',
    type: 'MULTIPLE_CHOICE',
    stage: 'MEDIO',
    gradeLevel: '3a serie',
    area: 'Linguagens e suas Tecnologias',
    component: 'Lingua Portuguesa',
    subject: 'Lingua Portuguesa',
    difficulty: 'MEDIUM',
    sourceType: 'GLOBAL_CURATED',
    sourceName: 'Banco autoral LiEnsina',
    sourceYear: 2026,
    visibility: 'GLOBAL',
    status: 'APPROVED',
    options: [
      { label: 'A', text: 'uma conclusao contraria a tese.', order: 1, isCorrect: false },
      { label: 'B', text: 'um argumento que justifica a opiniao.', order: 2, isCorrect: true },
      { label: 'C', text: 'uma informacao sem relacao com a tese.', order: 3, isCorrect: false },
      { label: 'D', text: 'uma descricao do espaco onde ocorre a acao.', order: 4, isCorrect: false },
      { label: 'E', text: 'uma citacao de autoridade.', order: 5, isCorrect: false },
    ],
    skills: [{ code: 'EM13LP05', description: 'Analisar, em textos argumentativos, posicionamentos assumidos, argumentos e estrategias de persuasao.', relevance: 'PRIMARY' }],
    descriptors: [{ program: 'SAEPI', code: 'D08', description: 'Estabelecer relacao entre tese e argumentos oferecidos para sustenta-la.', subject: 'Lingua Portuguesa', relevance: 'PRIMARY' }],
    metadata: { estimatedTimeSeconds: 90, hasImage: false, hasTable: false, hasFormula: false, keywords: ['argumentacao', 'tese', 'argumento'] },
  },
]

const allSeedQuestions = [...seedQuestions, ...additionalSeedQuestions]
const enemApiYears = Array.from({ length: 2023 - 2009 + 1 }, (_, index) => 2009 + index)

const questionImportPlans: QuestionImportPlan[] = [{
  id: 'question-import-plan-inep-enem',
  sourceType: 'INEP_ENEM',
  officialSource: 'API ENEM.DEV',
  availableOfficialYears: enemApiYears,
  unavailableOfficialYears: [],
  reasonUnavailable: 'A integracao automatica usa a API enem.dev para os anos de 2009 a 2023.',
  recommendedAction: 'Buscar questoes por ano em https://api.enem.dev/v1/exams/{ano}/questions, persistir no banco com sourceYear, sourceExternalId, disciplina, numero da questao, arquivos e gabarito.',
  itemsToImport: enemApiYears.map((year) => ({
    sourceYear: year,
    examDay: 0,
    notebookColor: 'API',
    quantity: 0,
    importedCount: 0,
    sourceUrl: `https://api.enem.dev/v1/exams/${year}/questions`,
    status: 'PENDING_IMPORT' as const,
  })),
  active: true,
  metadata: {
    sourceApi: 'https://api.enem.dev/v1/exams',
    supportedYears: enemApiYears,
  },
  createdAt: seedCreatedAt,
  updatedAt: seedCreatedAt,
}]

export function buildQuestionBankSeed(): QuestionBankSeed {
  const curriculumBases: CurriculumBase[] = [{
    id: curriculumBaseId,
    name: 'Base Nacional Comum Curricular',
    code: 'BNCC',
    description: 'Documento normativo que define aprendizagens essenciais da Educacao Basica.',
    sourceUrl: 'https://basenacionalcomum.mec.gov.br/',
    isOfficial: true,
    active: true,
    metadata: {},
    createdAt: seedCreatedAt,
    updatedAt: seedCreatedAt,
  }]
  const assessmentPrograms = new Map<string, AssessmentProgram>()
  const assessmentMatrices = new Map<string, AssessmentMatrix>()
  const assessmentDescriptors = new Map<string, AssessmentDescriptor>()
  const curriculumSkills = new Map<string, CurriculumSkill>()

  const questions = allSeedQuestions.map((seedQuestion, questionIndex) => {
    const questionSeedKey = `${seedQuestion.sourceType}|${seedQuestion.sourceYear}|${seedQuestion.title}|${seedQuestion.statement}`
    const questionId = stableId('question', questionSeedKey)
    const createdAt = new Date(Date.parse(seedCreatedAt) + questionIndex * 60 * 1000).toISOString()
    const skills = seedQuestion.skills.map((seedSkill) => {
      const skillId = stableId('skill', seedSkill.code)
      if (!curriculumSkills.has(seedSkill.code)) {
        curriculumSkills.set(seedSkill.code, {
          id: skillId,
          baseId: curriculumBaseId,
          code: seedSkill.code,
          description: seedSkill.description,
          stage: seedQuestion.stage,
          gradeLevel: seedQuestion.gradeLevel,
          area: seedQuestion.area,
          component: seedQuestion.component,
          thematicUnit: '',
          knowledgeObject: '',
          competence: null,
          sourceUrl: 'https://basenacionalcomum.mec.gov.br/',
          active: true,
          metadata: {},
          createdAt: seedCreatedAt,
          updatedAt: seedCreatedAt,
        })
      }
      return { ...curriculumSkills.get(seedSkill.code)!, relevance: seedSkill.relevance }
    })
    const descriptors = seedQuestion.descriptors.map((seedDescriptor) => {
      const programId = stableId('assessment-program', seedDescriptor.program)
      if (!assessmentPrograms.has(seedDescriptor.program)) {
        assessmentPrograms.set(seedDescriptor.program, {
          id: programId,
          name: seedDescriptor.program,
          code: seedDescriptor.program,
          description: `Programa de avaliacao ${seedDescriptor.program}.`,
          sourceUrl: null,
          isOfficial: true,
          active: true,
          metadata: {},
          createdAt: seedCreatedAt,
          updatedAt: seedCreatedAt,
        })
      }
      const matrixKey = `${seedDescriptor.program}|${seedQuestion.stage}|${seedQuestion.gradeLevel}|${seedDescriptor.subject}`
      const matrixId = stableId('assessment-matrix', matrixKey)
      if (!assessmentMatrices.has(matrixKey)) {
        assessmentMatrices.set(matrixKey, {
          id: matrixId,
          programId,
          name: `${seedDescriptor.program} - ${seedDescriptor.subject} - ${seedQuestion.gradeLevel}`,
          year: seedQuestion.sourceYear,
          stage: seedQuestion.stage,
          gradeLevel: seedQuestion.gradeLevel,
          subject: seedDescriptor.subject,
          area: seedQuestion.area,
          sourceUrl: null,
          active: true,
          metadata: {},
          createdAt: seedCreatedAt,
          updatedAt: seedCreatedAt,
        })
      }
      const descriptorKey = `${matrixKey}|${seedDescriptor.code}`
      const descriptorId = stableId('assessment-descriptor', descriptorKey)
      if (!assessmentDescriptors.has(descriptorKey)) {
        assessmentDescriptors.set(descriptorKey, {
          id: descriptorId,
          matrixId,
          code: seedDescriptor.code,
          description: seedDescriptor.description,
          topic: seedDescriptor.subject,
          axis: seedDescriptor.subject,
          order: Number(seedDescriptor.code.replace(/\D/g, '')) || 0,
          active: true,
          metadata: {},
          createdAt: seedCreatedAt,
          updatedAt: seedCreatedAt,
        })
      }

      return {
        ...assessmentDescriptors.get(descriptorKey)!,
        program: seedDescriptor.program,
        matrix: assessmentMatrices.get(matrixKey)!.name,
        relevance: seedDescriptor.relevance,
      }
    })

    return {
      id: questionId,
      schoolId: globalSchoolId,
      networkId: globalNetworkId,
      createdById: systemUserId,
      title: seedQuestion.title,
      context: seedQuestion.context,
      statement: seedQuestion.statement,
      explanation: seedQuestion.explanation,
      type: seedQuestion.type,
      stage: seedQuestion.stage,
      gradeLevel: seedQuestion.gradeLevel,
      area: seedQuestion.area,
      component: seedQuestion.component,
      subject: seedQuestion.subject,
      difficulty: seedQuestion.difficulty,
      sourceType: seedQuestion.sourceType,
      sourceName: seedQuestion.sourceName,
      sourceYear: seedQuestion.sourceYear,
      sourceExternalId: `liensina-${slug(questionSeedKey)}`,
      sourceUrl: null,
      licenseNotes: 'Banco autoral LiEnsina para uso educacional interno.',
      visibility: seedQuestion.visibility,
      status: seedQuestion.status,
      isEditable: false,
      reviewedById: systemUserId,
      reviewedAt: seedCreatedAt,
      createdAt,
      updatedAt: createdAt,
      archivedAt: null,
      metadata: seedQuestion.metadata,
      options: seedQuestion.options.map((option) => ({
        id: `${questionId}-option-${option.label.toLowerCase()}`,
        questionId,
        label: option.label,
        text: option.text,
        order: option.order,
        isCorrect: option.isCorrect,
        createdAt,
        updatedAt: createdAt,
      })),
      skills,
      descriptors,
      attachments: [],
      reviews: [{
        id: `${questionId}-review-1`,
        questionId,
        reviewerId: systemUserId,
        status: 'APPROVED',
        comment: 'Questao aprovada no seed autoral do LiEnsina.',
        reviewedAt: seedCreatedAt,
      }],
    } satisfies Question
  })

  return {
    curriculumBases,
    curriculumSkills: Array.from(curriculumSkills.values()),
    assessmentPrograms: Array.from(assessmentPrograms.values()),
    assessmentMatrices: Array.from(assessmentMatrices.values()),
    assessmentDescriptors: Array.from(assessmentDescriptors.values()),
    questions,
    questionImportPlans,
  }
}

function stableId(prefix: string, value: string) {
  return `${prefix}-${slug(value)}`.slice(0, 96)
}

function slug(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 72)
}
